language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
  - yarn
  - yarn global add firebase-tools
script:
  - yarn build
  # NOTE: Add tests
  # - yarn test:coverage
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy
  on:
    all_branches: true