language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_ac9b50f07c40_key -iv $encrypted_ac9b50f07c40_iv
  -in service-account-credentials.json.enc -out functions/service-account-credentials.json
  -d
install:
  - cd functions
  - yarn
  - yarn global add firebase-tools
script:
  - yarn build
before_deploy:
  - firebase use default
deploy:
  keyfile: functions/service-account-credentials.json
  project: bibic-vendeghazak-api
  provider: gae
  skip_cleanup: true
  on:
    all_branches: true
