language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_ac9b50f07c40_key -iv $encrypted_ac9b50f07c40_iv
  -in service-account-credentials.json.enc -out functions/service-account-credentials.json
  -d
install:
- yarn global add firebase-tools
- cd functions
- yarn
script:
- yarn bolt
- yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy -P default --token $FIREBASE_TOKEN
  on:
    branch: master