language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- cd functions
- yarn
- yarn global add firebase-tools
script:
- yarn build
before_deploy:
- openssl aes-256-cbc -K $encrypted_ac9b50f07c40_key -iv $encrypted_ac9b50f07c40_iv
  -in ../service-account-credentials.json.enc -out service-account-credentials.json
  -d
- firebase use default
deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: master